# -*- coding: utf-8 -*-
"""Python Data Analytics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Phg2-v4rjatpm7wJaYhRCiJ7dmngsKOt
"""

import pandas as pd
import numpy as np

df = pd.DataFrame(pd.read_csv('/train (1).xls'))
df.head()

df.shape

df.isnull().sum()

drop_col = df.isnull().sum()[df.isnull().sum()>(35/100 * df.shape[0])]
drop_col

drop_col.index

df.fillna(df.mean(), inplace=True)
df.isnull().sum()

df['Embarked'].describe()

df['Embarked'].fillna("S", inplace=True)
df.isnull().sum()

df.corr()

df['FamilyMan'] = df['SibSp'] + df['Parch']
df.drop(['SibSp', 'Parch'], axis=1, inplace=True)
df.corr()

df['SinglePerson'] = [0 if df['FamilyMan'][i]>0 else 1 for i in df.index]
df.head()

df.groupby(['SinglePerson'])['Survived'].mean()

df[['SinglePerson', 'Fare']].corr()

df['Sex'] = [0 if df['Sex'][i]=='male' else 1 for i in df.index] 
df.groupby(['Sex'])['Survived'].mean()
# 0 for male and 1 for female

df.groupby(['Embarked'])['Survived'].mean()